title: CV Arxiv Daily
description: Automatically Update CV Papers Daily using Github Actions (Update Every 12th hours)
show_downloads: true
#theme: jekyll-theme-slate

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

github:
  zip_url: https://github.com/LJoson/arXiv_daily
  another_url: https://github.com/LJoson/arXiv_daily
